//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SQLite;


namespace DCS.DCSTables
{


    public partial class tblBitmap : SQLiteTable
	{
		
		#region Static SQL String Memebers
		/// <remarks>This _databasename represents the full INSERT INTO string for the table tblBitmap.</remarks>
		internal static string SQL_Insert = @"INSERT INTO [tblBitmap] ([BitmapName], [DisplayID], [oIndex], [left], [top], [right], [bottom], [Transparent], [Rotation], [LockPosition], [LockEdit], [Layer], [LastRev], [Action], [Expression], [Argument], [CompiledExp], [validexpression]) VALUES(@BitmapName, @DisplayID, @oIndex, @left, @top, @right, @bottom, @Transparent, @Rotation, @LockPosition, @LockEdit, @Layer, @LastRev, @Action, @Expression, @Argument, @CompiledExp, @validexpression) ; select last_insert_rowid(); ";
		
		/// <remarks>This _databasename represents the full UPDATE string for the table tblBitmap, with the WHERE clause.</remarks>
		internal static string SQL_Update = @"UPDATE [tblBitmap] SET [BitmapName] = @BitmapName, [DisplayID] = @DisplayID, [oIndex] = @oIndex, [left] = @left, [top] = @top, [right] = @right, [bottom] = @bottom, [Transparent] = @Transparent, [Rotation] = @Rotation, [LockPosition] = @LockPosition, [LockEdit] = @LockEdit, [Layer] = @Layer, [LastRev] = @LastRev, [Action] = @Action, [Expression] = @Expression, [Argument] = @Argument, [CompiledExp] = @CompiledExp, [validexpression] = @validexpression WHERE [ID]=@ID ";
		
		/// <remarks>This _databasename represents the full SELECT string for the table tblBitmap, with the WHERE clause.</remarks>
		internal static string SQL_Select = "SELECT [BitmapName], [DisplayID], [oIndex], [left], [top], [right], [bottom], [Tr" +
			"ansparent], [Rotation], [LockPosition], [LockEdit], [Layer], [LastRev], [Action]" +
			", [Expression], [Argument], [CompiledExp], [validexpression] FROM [tblBitmap] WH" +
			"ERE [ID]=@ID ";
		
		/// <remarks>This _databasename represents the DELETE string for the table tblBitmap, with the WHERE clause.</remarks>
		internal static string SQL_Delete = "DELETE FROM [tblBitmap] WHERE [ID]=@ID ";
		#endregion
		
		#region Tables Memebers
		/// <remarks>SQL Type:System.Int64</remarks>
		private long _ID = -1;
		
		[DisplayName("ID")]
		[Category("Primary Key")]
		public long ID
		{
			get
			{
				return _ID;
			}
			set
			{
				_ID = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _BitmapName = "";
		
		[DisplayName("Bitmap Name")]
		[Category("Column")]
		public string BitmapName
		{
			get
			{
				return _BitmapName;
			}
			set
			{
				_BitmapName = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int64</remarks>
		private long _DisplayID = -1;
		
		[DisplayName("Display ID")]
		[Category("Foreign Key")]
		public long DisplayID
		{
			get
			{
				return _DisplayID;
			}
			set
			{
				_DisplayID = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _oIndex;
		
		[DisplayName("o Index")]
		[Category("Column")]
		public int oIndex
		{
			get
			{
				return _oIndex;
			}
			set
			{
				_oIndex = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _left;
		
		[DisplayName("left")]
		[Category("Column")]
		public int left
		{
			get
			{
				return _left;
			}
			set
			{
				_left = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _top;
		
		[DisplayName("top")]
		[Category("Column")]
		public int top
		{
			get
			{
				return _top;
			}
			set
			{
				_top = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _right;
		
		[DisplayName("right")]
		[Category("Column")]
		public int right
		{
			get
			{
				return _right;
			}
			set
			{
				_right = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _bottom;
		
		[DisplayName("bottom")]
		[Category("Column")]
		public int bottom
		{
			get
			{
				return _bottom;
			}
			set
			{
				_bottom = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _Transparent;
		
		[DisplayName("Transparent")]
		[Category("Column")]
		public bool Transparent
		{
			get
			{
				return _Transparent;
			}
			set
			{
				_Transparent = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _Rotation;
		
		[DisplayName("Rotation")]
		[Category("Column")]
		public int Rotation
		{
			get
			{
				return _Rotation;
			}
			set
			{
				_Rotation = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _LockPosition;
		
		[DisplayName("Lock Position")]
		[Category("Column")]
		public bool LockPosition
		{
			get
			{
				return _LockPosition;
			}
			set
			{
				_LockPosition = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _LockEdit;
		
		[DisplayName("Lock Edit")]
		[Category("Column")]
		public bool LockEdit
		{
			get
			{
				return _LockEdit;
			}
			set
			{
				_LockEdit = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _Layer;
		
		[DisplayName("Layer")]
		[Category("Column")]
		public int Layer
		{
			get
			{
				return _Layer;
			}
			set
			{
				_Layer = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _LastRev;
		
		[DisplayName("Last Rev")]
		[Category("Column")]
		public bool LastRev
		{
			get
			{
				return _LastRev;
			}
			set
			{
				_LastRev = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _Action = "";
		
		[DisplayName("Action")]
		[Category("Column")]
		public string Action
		{
			get
			{
				return _Action;
			}
			set
			{
				_Action = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _Expression = "";
		
		[DisplayName("Expression")]
		[Category("Column")]
		public string Expression
		{
			get
			{
				return _Expression;
			}
			set
			{
				_Expression = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _Argument = "";
		
		[DisplayName("Argument")]
		[Category("Column")]
		public string Argument
		{
			get
			{
				return _Argument;
			}
			set
			{
				_Argument = value;
			}
		}
		
		/// <remarks>SQL Type:System.Byte[]</remarks>
		private byte[] _CompiledExp;
		
		[DisplayName("Compiled Exp")]
		[Category("Column")]
		public byte[] CompiledExp
		{
			get
			{
				return _CompiledExp;
			}
			set
			{
				_CompiledExp = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _validexpression;
		
		[DisplayName("validexpression")]
		[Category("Column")]
		public bool validexpression
		{
			get
			{
				return _validexpression;
			}
			set
			{
				_validexpression = value;
			}
		}
		#endregion
		
		#region Related Objects
		/// <remarks>Represents the foreign key object</remarks>
		private tblDisplay _DisplayID_tblDisplay;
		
		[Description("Represents the foreign key object of the type DisplayID")]
		public tblDisplay m_DisplayID_tblDisplay
		{
			get
			{
				return _DisplayID_tblDisplay;
			}
			set
			{
				_DisplayID_tblDisplay = value;
			}
		}
		#endregion
		
		#region Public Methods
		public int Delete()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreDeleteTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				SQLiteCommand ComSync = Common.Conn.CreateCommand();
				Com.CommandText = tblBitmap.SQL_Delete;
				ComSync.CommandText = "PRAGMA foreign_keys=ON";
				Com.Parameters.AddRange(GetSqlParameters());
				ComSync.ExecuteNonQuery();
				int rowseffected = Com.ExecuteNonQuery();
				ComSync.Dispose();
				Com.Dispose();
				this.PostDeleteTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Select()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblBitmap.SQL_Select;
				Com.Parameters.AddRange(GetSqlParameters());
				SQLiteDataReader rs = Com.ExecuteReader();
				for (
				; rs.Read(); 
				)
				{
					AddFromRecordSet(rs);
				}
				rs.Close();
				rs.Dispose();
				Com.Dispose();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Insert()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreInsertTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblBitmap.SQL_Insert;
				Com.Parameters.AddRange(GetSqlParameters());
				ID = ((long)(Convert.ToInt64(Com.ExecuteScalar())));
				Com.Dispose();
				this.PostInsertTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Update()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreUpdateTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblBitmap.SQL_Update;
				Com.Parameters.AddRange(GetSqlParameters());
				int rowseffected = Com.ExecuteNonQuery();
				Com.Dispose();
				this.PostUpdateTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public tblBitmap()
		{
		}
		#endregion
		
		#region Private Methods
		private SQLiteParameter[] GetSqlParameters()
		{
			List<SQLiteParameter> SqlParmColl = new List<SQLiteParameter>();
			try
			{
				SqlParmColl.Add(CommonDB.AddSqlParm("@ID", ID, DbType.Int64));
				SqlParmColl.Add(CommonDB.AddSqlParm("@BitmapName", BitmapName, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@DisplayID", DisplayID, DbType.Int64));
				SqlParmColl.Add(CommonDB.AddSqlParm("@oIndex", oIndex, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@left", left, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@top", top, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@right", right, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@bottom", bottom, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Transparent", Transparent, DbType.Boolean));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Rotation", Rotation, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@LockPosition", LockPosition, DbType.Boolean));
				SqlParmColl.Add(CommonDB.AddSqlParm("@LockEdit", LockEdit, DbType.Boolean));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Layer", Layer, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@LastRev", LastRev, DbType.Boolean));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Action", Action, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Expression", Expression, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Argument", Argument, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@CompiledExp", CompiledExp, DbType.Binary));
				SqlParmColl.Add(CommonDB.AddSqlParm("@validexpression", validexpression, DbType.Boolean));
				return SqlParmColl.ToArray();
			}
			catch (SQLiteException Exc)
			{
				throw Exc;
			}
		}
		
		public void AddFromRecordSet(SQLiteDataReader rs)
		{
			try
			{
				// if value from the recordset, to the ID _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("ID")) == false))
				{
					ID = ((long)(Convert.ChangeType(rs["ID"], typeof(long))));
				}
				// if value from the recordset, to the BitmapName _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("BitmapName")) == false))
				{
					BitmapName = ((string)(Convert.ChangeType(rs["BitmapName"], typeof(string))));
				}
				// if value from the recordset, to the DisplayID _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("DisplayID")) == false))
				{
					DisplayID = ((long)(Convert.ChangeType(rs["DisplayID"], typeof(long))));
				}
				// if value from the recordset, to the oIndex _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("oIndex")) == false))
				{
					oIndex = ((int)(Convert.ChangeType(rs["oIndex"], typeof(int))));
				}
				// if value from the recordset, to the left _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("left")) == false))
				{
					left = ((int)(Convert.ChangeType(rs["left"], typeof(int))));
				}
				// if value from the recordset, to the top _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("top")) == false))
				{
					top = ((int)(Convert.ChangeType(rs["top"], typeof(int))));
				}
				// if value from the recordset, to the right _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("right")) == false))
				{
					right = ((int)(Convert.ChangeType(rs["right"], typeof(int))));
				}
				// if value from the recordset, to the bottom _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("bottom")) == false))
				{
					bottom = ((int)(Convert.ChangeType(rs["bottom"], typeof(int))));
				}
				// if value from the recordset, to the Transparent _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Transparent")) == false))
				{
					Transparent = ((bool)(Convert.ChangeType(rs["Transparent"], typeof(bool))));
				}
				// if value from the recordset, to the Rotation _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Rotation")) == false))
				{
					Rotation = ((int)(Convert.ChangeType(rs["Rotation"], typeof(int))));
				}
				// if value from the recordset, to the LockPosition _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("LockPosition")) == false))
				{
					LockPosition = ((bool)(Convert.ChangeType(rs["LockPosition"], typeof(bool))));
				}
				// if value from the recordset, to the LockEdit _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("LockEdit")) == false))
				{
					LockEdit = ((bool)(Convert.ChangeType(rs["LockEdit"], typeof(bool))));
				}
				// if value from the recordset, to the Layer _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Layer")) == false))
				{
					Layer = ((int)(Convert.ChangeType(rs["Layer"], typeof(int))));
				}
				// if value from the recordset, to the LastRev _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("LastRev")) == false))
				{
					LastRev = ((bool)(Convert.ChangeType(rs["LastRev"], typeof(bool))));
				}
				// if value from the recordset, to the Action _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Action")) == false))
				{
					Action = ((string)(Convert.ChangeType(rs["Action"], typeof(string))));
				}
				// if value from the recordset, to the Expression _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Expression")) == false))
				{
					Expression = ((string)(Convert.ChangeType(rs["Expression"], typeof(string))));
				}
				// if value from the recordset, to the Argument _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Argument")) == false))
				{
					Argument = ((string)(Convert.ChangeType(rs["Argument"], typeof(string))));
				}
				// if value from the recordset, to the CompiledExp _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("CompiledExp")) == false))
				{
					CompiledExp = ((byte[])(Convert.ChangeType(rs["CompiledExp"], typeof(byte[]))));
				}
				// if value from the recordset, to the validexpression _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("validexpression")) == false))
				{
					validexpression = ((bool)(Convert.ChangeType(rs["validexpression"], typeof(bool))));
				}
			}
			catch (SQLiteException sqlExc)
			{
				throw sqlExc;
			}
			catch (Exception Exc)
			{
				throw Exc;
			}
		}
		
		public override void AddFromString(string[] _strs, string arg1, ref string _log)
		{
			try
			{
				this.PreAddFromString(ref _log);
				int i;
				i = this.ColumnExistInHeader("BitmapName");
				if ((i >= 0))
				{
					BitmapName = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("DisplayID");
				if ((i >= 0))
				{
					DisplayID = ((long)(Convert.ChangeType(_strs[i], typeof(long))));
				}
				i = this.ColumnExistInHeader("oIndex");
				if ((i >= 0))
				{
					oIndex = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("left");
				if ((i >= 0))
				{
					left = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("top");
				if ((i >= 0))
				{
					top = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("right");
				if ((i >= 0))
				{
					right = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("bottom");
				if ((i >= 0))
				{
					bottom = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("Transparent");
				if ((i >= 0))
				{
					Transparent = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				i = this.ColumnExistInHeader("Rotation");
				if ((i >= 0))
				{
					Rotation = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("LockPosition");
				if ((i >= 0))
				{
					LockPosition = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				i = this.ColumnExistInHeader("LockEdit");
				if ((i >= 0))
				{
					LockEdit = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				i = this.ColumnExistInHeader("Layer");
				if ((i >= 0))
				{
					Layer = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("LastRev");
				if ((i >= 0))
				{
					LastRev = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				i = this.ColumnExistInHeader("Action");
				if ((i >= 0))
				{
					Action = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("Expression");
				if ((i >= 0))
				{
					Expression = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("Argument");
				if ((i >= 0))
				{
					Argument = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("CompiledExp");
				if ((i >= 0))
				{
					CompiledExp = ((byte[])(Convert.ChangeType(_strs[i], typeof(byte[]))));
				}
				i = this.ColumnExistInHeader("validexpression");
				if ((i >= 0))
				{
					validexpression = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				this.PostAddFromString(ref _log);
			}
			catch (SQLiteException sqlExc)
			{
				throw sqlExc;
			}
			catch (Exception Exc)
			{
				throw Exc;
			}
		}
		#endregion
	}
	
	public delegate void tblBitmapChangedEventHandler(object sender, System.EventArgs e);
	
	public partial class tblBitmapCollection : SQLiteTableCollection
	{
		
		/// <remarks>SQL Type:tblBitmapChangedEventHandler</remarks>
		public event tblBitmapChangedEventHandler tblBitmapChanged;
		
		/// <remarks>Represents the foreign key object</remarks>
		private tblDisplay _DisplayID_tblDisplay;
		
		[Description("Represents the foreign key object of the type DisplayID")]
		public tblDisplay m_DisplayID_tblDisplay
		{
			get
			{
				return _DisplayID_tblDisplay;
			}
			set
			{
				_DisplayID_tblDisplay = value;
			}
		}
		
		[Description("Constructor")]
		public tblBitmapCollection(tblDisplay _parent)
		{
			_DisplayID_tblDisplay = _parent;
		}
		
		[Description("Invoke the Changed event; called whenever list changes")]
		protected virtual void OntblBitmapChanged(System.EventArgs e)
		{
			if (tblBitmapChanged != null)
			{
				this.tblBitmapChanged(this, e);
			}
		}
		
		[Description("Gets a  tblBitmap from the collection.")]
		public tblBitmap this[int index]
		{
			get
			{
				return ((tblBitmap)(List[index]));
			}
			set
			{
				List[index] = value;
				this.OntblBitmapChanged(EventArgs.Empty);
			}
		}
		
		[Description("Gets a  tblBitmap from the collection.")]
		public tblBitmap Get(int index)
		{
			return ((tblBitmap)(List[index]));
		}
		
		[Description("Adds a new tblBitmap to the collection.")]
		public void Add(tblBitmap item)
		{
			List.Add(item);
			this.OntblBitmapChanged(EventArgs.Empty);
		}
		
		[Description("Removes a tblBitmap from the collection.")]
		public void Remove(tblBitmap item)
		{
			List.Remove(item);
			this.OntblBitmapChanged(EventArgs.Empty);
		}
		
		[Description("Inserts an tblBitmap into the collection at the specified index.")]
		public void Insert(int index, tblBitmap item)
		{
			List.Insert(index, item);
			this.OntblBitmapChanged(EventArgs.Empty);
		}
		
		[Description("Returns the index value of the tblBitmap class in the collection.")]
		public int IndexOf(tblBitmap item)
		{
			return List.IndexOf(item);
		}
		
		[Description("Returns true if the tblBitmap class is present in the collection.")]
		public bool Contains(tblBitmap item)
		{
			return List.Contains(item);
		}
	}
}
