//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SQLite;
using System.Drawing;


namespace DCS.DCSTables
{


    public partial class tblMeter : SQLiteTable
	{
		
		#region Static SQL String Memebers
		/// <remarks>This _databasename represents the full INSERT INTO string for the table tblMeter.</remarks>
		internal static string SQL_Insert = @"INSERT INTO [tblMeter] ([DisplayID], [oIndex], [DlgType], [DlgIndex], [Left], [Right], [Top], [Bottom], [ViewUnit], [ViewLim], [ViewLable], [NeedleColor], [MeterValue], [Font], [FontColor], [LimFont], [LimFontColor], [MeterValueID], [LastRev], [Layer], [CompiledExp], [validexpression]) VALUES(@DisplayID, @oIndex, @DlgType, @DlgIndex, @Left, @Right, @Top, @Bottom, @ViewUnit, @ViewLim, @ViewLable, @NeedleColor, @MeterValue, @Font, @FontColor, @LimFont, @LimFontColor, @MeterValueID, @LastRev, @Layer, @CompiledExp, @validexpression) ; select last_insert_rowid(); ";
		
		/// <remarks>This _databasename represents the full UPDATE string for the table tblMeter, with the WHERE clause.</remarks>
		internal static string SQL_Update = @"UPDATE [tblMeter] SET [DisplayID] = @DisplayID, [oIndex] = @oIndex, [DlgType] = @DlgType, [DlgIndex] = @DlgIndex, [Left] = @Left, [Right] = @Right, [Top] = @Top, [Bottom] = @Bottom, [ViewUnit] = @ViewUnit, [ViewLim] = @ViewLim, [ViewLable] = @ViewLable, [NeedleColor] = @NeedleColor, [MeterValue] = @MeterValue, [Font] = @Font, [FontColor] = @FontColor, [LimFont] = @LimFont, [LimFontColor] = @LimFontColor, [MeterValueID] = @MeterValueID, [LastRev] = @LastRev, [Layer] = @Layer, [CompiledExp] = @CompiledExp, [validexpression] = @validexpression WHERE [ID]=@ID ";
		
		/// <remarks>This _databasename represents the full SELECT string for the table tblMeter, with the WHERE clause.</remarks>
		internal static string SQL_Select = @"SELECT [DisplayID], [oIndex], [DlgType], [DlgIndex], [Left], [Right], [Top], [Bottom], [ViewUnit], [ViewLim], [ViewLable], [NeedleColor], [MeterValue], [Font], [FontColor], [LimFont], [LimFontColor], [MeterValueID], [LastRev], [Layer], [CompiledExp], [validexpression] FROM [tblMeter] WHERE [ID]=@ID ";
		
		/// <remarks>This _databasename represents the DELETE string for the table tblMeter, with the WHERE clause.</remarks>
		internal static string SQL_Delete = "DELETE FROM [tblMeter] WHERE [ID]=@ID ";
		#endregion
		
		#region Tables Memebers
		/// <remarks>SQL Type:System.Int64</remarks>
		private long _ID = -1;
		
		[DisplayName("ID")]
		[Category("Primary Key")]
		public long ID
		{
			get
			{
				return _ID;
			}
			set
			{
				_ID = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int64</remarks>
		private long _DisplayID = -1;
		
		[DisplayName("Display ID")]
		[Category("Foreign Key")]
		public long DisplayID
		{
			get
			{
				return _DisplayID;
			}
			set
			{
				_DisplayID = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _oIndex;
		
		[DisplayName("o Index")]
		[Category("Column")]
		public int oIndex
		{
			get
			{
				return _oIndex;
			}
			set
			{
				_oIndex = value;
			}
		}
		
		/// <remarks>SQL Type:System.Byte</remarks>
		private byte _DlgType;
		
		[DisplayName("Dlg Type")]
		[Category("Column")]
		public byte DlgType
		{
			get
			{
				return _DlgType;
			}
			set
			{
				_DlgType = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _DlgIndex;
		
		[DisplayName("Dlg Index")]
		[Category("Column")]
		public int DlgIndex
		{
			get
			{
				return _DlgIndex;
			}
			set
			{
				_DlgIndex = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _Left;
		
		[DisplayName("Left")]
		[Category("Column")]
		public int Left
		{
			get
			{
				return _Left;
			}
			set
			{
				_Left = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _Right;
		
		[DisplayName("Right")]
		[Category("Column")]
		public int Right
		{
			get
			{
				return _Right;
			}
			set
			{
				_Right = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _Top;
		
		[DisplayName("Top")]
		[Category("Column")]
		public int Top
		{
			get
			{
				return _Top;
			}
			set
			{
				_Top = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _Bottom;
		
		[DisplayName("Bottom")]
		[Category("Column")]
		public int Bottom
		{
			get
			{
				return _Bottom;
			}
			set
			{
				_Bottom = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _ViewUnit;
		
		[DisplayName("View Unit")]
		[Category("Column")]
		public bool ViewUnit
		{
			get
			{
				return _ViewUnit;
			}
			set
			{
				_ViewUnit = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _ViewLim;
		
		[DisplayName("View Lim")]
		[Category("Column")]
		public bool ViewLim
		{
			get
			{
				return _ViewLim;
			}
			set
			{
				_ViewLim = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _ViewLable;
		
		[DisplayName("View Lable")]
		[Category("Column")]
		public bool ViewLable
		{
			get
			{
				return _ViewLable;
			}
			set
			{
				_ViewLable = value;
			}
		}
		
		/// <remarks>SQL Type:System.Drawing.Color</remarks>
		private System.Drawing.Color _NeedleColor;
		
		[DisplayName("Needle Color")]
		[Category("Column")]
		public System.Drawing.Color NeedleColor
		{
			get
			{
				return _NeedleColor;
			}
			set
			{
				_NeedleColor = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _MeterValue = "";
		
		[DisplayName("Meter Value")]
		[Category("Column")]
		public string MeterValue
		{
			get
			{
				return _MeterValue;
			}
			set
			{
				_MeterValue = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _Font = "";
		
		[DisplayName("Font")]
		[Category("Column")]
		public string Font
		{
			get
			{
				return _Font;
			}
			set
			{
				_Font = value;
			}
		}
		
		/// <remarks>SQL Type:System.Drawing.Color</remarks>
		private System.Drawing.Color _FontColor;
		
		[DisplayName("Font Color")]
		[Category("Column")]
		public System.Drawing.Color FontColor
		{
			get
			{
				return _FontColor;
			}
			set
			{
				_FontColor = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _LimFont = "";
		
		[DisplayName("Lim Font")]
		[Category("Column")]
		public string LimFont
		{
			get
			{
				return _LimFont;
			}
			set
			{
				_LimFont = value;
			}
		}
		
		/// <remarks>SQL Type:System.Drawing.Color</remarks>
		private System.Drawing.Color _LimFontColor;
		
		[DisplayName("Lim Font Color")]
		[Category("Column")]
		public System.Drawing.Color LimFontColor
		{
			get
			{
				return _LimFontColor;
			}
			set
			{
				_LimFontColor = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _MeterValueID;
		
		[DisplayName("Meter Value ID")]
		[Category("Column")]
		public int MeterValueID
		{
			get
			{
				return _MeterValueID;
			}
			set
			{
				_MeterValueID = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _LastRev;
		
		[DisplayName("Last Rev")]
		[Category("Column")]
		public bool LastRev
		{
			get
			{
				return _LastRev;
			}
			set
			{
				_LastRev = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _Layer;
		
		[DisplayName("Layer")]
		[Category("Column")]
		public int Layer
		{
			get
			{
				return _Layer;
			}
			set
			{
				_Layer = value;
			}
		}
		
		/// <remarks>SQL Type:System.Byte[]</remarks>
		private byte[] _CompiledExp;
		
		[DisplayName("Compiled Exp")]
		[Category("Column")]
		public byte[] CompiledExp
		{
			get
			{
				return _CompiledExp;
			}
			set
			{
				_CompiledExp = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _validexpression;
		
		[DisplayName("validexpression")]
		[Category("Column")]
		public bool validexpression
		{
			get
			{
				return _validexpression;
			}
			set
			{
				_validexpression = value;
			}
		}
		#endregion
		
		#region Related Objects
		/// <remarks>Represents the foreign key object</remarks>
		private tblDisplay _DisplayID_tblDisplay;
		
		[Description("Represents the foreign key object of the type DisplayID")]
		public tblDisplay m_DisplayID_tblDisplay
		{
			get
			{
				return _DisplayID_tblDisplay;
			}
			set
			{
				_DisplayID_tblDisplay = value;
			}
		}
		#endregion
		
		#region Public Methods
		public int Delete()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreDeleteTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				SQLiteCommand ComSync = Common.Conn.CreateCommand();
				Com.CommandText = tblMeter.SQL_Delete;
				ComSync.CommandText = "PRAGMA foreign_keys=ON";
				Com.Parameters.AddRange(GetSqlParameters());
				ComSync.ExecuteNonQuery();
				int rowseffected = Com.ExecuteNonQuery();
				ComSync.Dispose();
				Com.Dispose();
				this.PostDeleteTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Select()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblMeter.SQL_Select;
				Com.Parameters.AddRange(GetSqlParameters());
				SQLiteDataReader rs = Com.ExecuteReader();
				for (
				; rs.Read(); 
				)
				{
					AddFromRecordSet(rs);
				}
				rs.Close();
				rs.Dispose();
				Com.Dispose();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Insert()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreInsertTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblMeter.SQL_Insert;
				Com.Parameters.AddRange(GetSqlParameters());
				ID = ((long)(Convert.ToInt64(Com.ExecuteScalar())));
				Com.Dispose();
				this.PostInsertTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Update()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreUpdateTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblMeter.SQL_Update;
				Com.Parameters.AddRange(GetSqlParameters());
				int rowseffected = Com.ExecuteNonQuery();
				Com.Dispose();
				this.PostUpdateTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public tblMeter()
		{
		}
		#endregion
		
		#region Private Methods
		private SQLiteParameter[] GetSqlParameters()
		{
			List<SQLiteParameter> SqlParmColl = new List<SQLiteParameter>();
			try
			{
				SqlParmColl.Add(CommonDB.AddSqlParm("@ID", ID, DbType.Int64));
				SqlParmColl.Add(CommonDB.AddSqlParm("@DisplayID", DisplayID, DbType.Int64));
				SqlParmColl.Add(CommonDB.AddSqlParm("@oIndex", oIndex, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@DlgType", DlgType, DbType.Byte));
				SqlParmColl.Add(CommonDB.AddSqlParm("@DlgIndex", DlgIndex, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Left", Left, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Right", Right, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Top", Top, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Bottom", Bottom, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@ViewUnit", ViewUnit, DbType.Boolean));
				SqlParmColl.Add(CommonDB.AddSqlParm("@ViewLim", ViewLim, DbType.Boolean));
				SqlParmColl.Add(CommonDB.AddSqlParm("@ViewLable", ViewLable, DbType.Boolean));
				SqlParmColl.Add(CommonDB.AddSqlParm("@NeedleColor", NeedleColor.ToArgb(), DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@MeterValue", MeterValue, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Font", Font, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@FontColor", FontColor.ToArgb(), DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@LimFont", LimFont, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@LimFontColor", LimFontColor.ToArgb(), DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@MeterValueID", MeterValueID, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@LastRev", LastRev, DbType.Boolean));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Layer", Layer, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@CompiledExp", CompiledExp, DbType.Binary));
				SqlParmColl.Add(CommonDB.AddSqlParm("@validexpression", validexpression, DbType.Boolean));
				return SqlParmColl.ToArray();
			}
			catch (SQLiteException Exc)
			{
				throw Exc;
			}
		}
		
		public void AddFromRecordSet(SQLiteDataReader rs)
		{
			try
			{
				// if value from the recordset, to the ID _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("ID")) == false))
				{
					ID = ((long)(Convert.ChangeType(rs["ID"], typeof(long))));
				}
				// if value from the recordset, to the DisplayID _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("DisplayID")) == false))
				{
					DisplayID = ((long)(Convert.ChangeType(rs["DisplayID"], typeof(long))));
				}
				// if value from the recordset, to the oIndex _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("oIndex")) == false))
				{
					oIndex = ((int)(Convert.ChangeType(rs["oIndex"], typeof(int))));
				}
				// if value from the recordset, to the DlgType _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("DlgType")) == false))
				{
					DlgType = ((byte)(Convert.ChangeType(rs["DlgType"], typeof(byte))));
				}
				// if value from the recordset, to the DlgIndex _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("DlgIndex")) == false))
				{
					DlgIndex = ((int)(Convert.ChangeType(rs["DlgIndex"], typeof(int))));
				}
				// if value from the recordset, to the Left _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Left")) == false))
				{
					Left = ((int)(Convert.ChangeType(rs["Left"], typeof(int))));
				}
				// if value from the recordset, to the Right _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Right")) == false))
				{
					Right = ((int)(Convert.ChangeType(rs["Right"], typeof(int))));
				}
				// if value from the recordset, to the Top _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Top")) == false))
				{
					Top = ((int)(Convert.ChangeType(rs["Top"], typeof(int))));
				}
				// if value from the recordset, to the Bottom _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Bottom")) == false))
				{
					Bottom = ((int)(Convert.ChangeType(rs["Bottom"], typeof(int))));
				}
				// if value from the recordset, to the ViewUnit _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("ViewUnit")) == false))
				{
					ViewUnit = ((bool)(Convert.ChangeType(rs["ViewUnit"], typeof(bool))));
				}
				// if value from the recordset, to the ViewLim _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("ViewLim")) == false))
				{
					ViewLim = ((bool)(Convert.ChangeType(rs["ViewLim"], typeof(bool))));
				}
				// if value from the recordset, to the ViewLable _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("ViewLable")) == false))
				{
					ViewLable = ((bool)(Convert.ChangeType(rs["ViewLable"], typeof(bool))));
				}
				// if value from the recordset, to the NeedleColor _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("NeedleColor")) == false))
				{
					NeedleColor = Color.FromArgb(((int)(Convert.ChangeType(rs["NeedleColor"], typeof(int)))));
				}
				// if value from the recordset, to the MeterValue _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("MeterValue")) == false))
				{
					MeterValue = ((string)(Convert.ChangeType(rs["MeterValue"], typeof(string))));
				}
				// if value from the recordset, to the Font _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Font")) == false))
				{
					Font = ((string)(Convert.ChangeType(rs["Font"], typeof(string))));
				}
				// if value from the recordset, to the FontColor _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("FontColor")) == false))
				{
					FontColor = Color.FromArgb(((int)(Convert.ChangeType(rs["FontColor"], typeof(int)))));
				}
				// if value from the recordset, to the LimFont _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("LimFont")) == false))
				{
					LimFont = ((string)(Convert.ChangeType(rs["LimFont"], typeof(string))));
				}
				// if value from the recordset, to the LimFontColor _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("LimFontColor")) == false))
				{
					LimFontColor = Color.FromArgb(((int)(Convert.ChangeType(rs["LimFontColor"], typeof(int)))));
				}
				// if value from the recordset, to the MeterValueID _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("MeterValueID")) == false))
				{
					MeterValueID = ((int)(Convert.ChangeType(rs["MeterValueID"], typeof(int))));
				}
				// if value from the recordset, to the LastRev _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("LastRev")) == false))
				{
					LastRev = ((bool)(Convert.ChangeType(rs["LastRev"], typeof(bool))));
				}
				// if value from the recordset, to the Layer _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Layer")) == false))
				{
					Layer = ((int)(Convert.ChangeType(rs["Layer"], typeof(int))));
				}
				// if value from the recordset, to the CompiledExp _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("CompiledExp")) == false))
				{
					CompiledExp = ((byte[])(Convert.ChangeType(rs["CompiledExp"], typeof(byte[]))));
				}
				// if value from the recordset, to the validexpression _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("validexpression")) == false))
				{
					validexpression = ((bool)(Convert.ChangeType(rs["validexpression"], typeof(bool))));
				}
			}
			catch (SQLiteException sqlExc)
			{
				throw sqlExc;
			}
			catch (Exception Exc)
			{
				throw Exc;
			}
		}
		
		public override void AddFromString(string[] _strs, string arg1, ref string _log)
		{
			try
			{
				this.PreAddFromString(ref _log);
				int i;
				i = this.ColumnExistInHeader("DisplayID");
				if ((i >= 0))
				{
					DisplayID = ((long)(Convert.ChangeType(_strs[i], typeof(long))));
				}
				i = this.ColumnExistInHeader("oIndex");
				if ((i >= 0))
				{
					oIndex = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("DlgType");
				if ((i >= 0))
				{
					DlgType = ((byte)(Convert.ChangeType(_strs[i], typeof(byte))));
				}
				i = this.ColumnExistInHeader("DlgIndex");
				if ((i >= 0))
				{
					DlgIndex = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("Left");
				if ((i >= 0))
				{
					Left = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("Right");
				if ((i >= 0))
				{
					Right = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("Top");
				if ((i >= 0))
				{
					Top = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("Bottom");
				if ((i >= 0))
				{
					Bottom = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("ViewUnit");
				if ((i >= 0))
				{
					ViewUnit = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				i = this.ColumnExistInHeader("ViewLim");
				if ((i >= 0))
				{
					ViewLim = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				i = this.ColumnExistInHeader("ViewLable");
				if ((i >= 0))
				{
					ViewLable = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				i = this.ColumnExistInHeader("NeedleColor");
				if ((i >= 0))
				{
					NeedleColor = Color.FromArgb(((int)(Convert.ChangeType(_strs[i], typeof(int)))));
				}
				i = this.ColumnExistInHeader("MeterValue");
				if ((i >= 0))
				{
					MeterValue = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("Font");
				if ((i >= 0))
				{
					Font = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("FontColor");
				if ((i >= 0))
				{
					FontColor = Color.FromArgb(((int)(Convert.ChangeType(_strs[i], typeof(int)))));
				}
				i = this.ColumnExistInHeader("LimFont");
				if ((i >= 0))
				{
					LimFont = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("LimFontColor");
				if ((i >= 0))
				{
					LimFontColor = Color.FromArgb(((int)(Convert.ChangeType(_strs[i], typeof(int)))));
				}
				i = this.ColumnExistInHeader("MeterValueID");
				if ((i >= 0))
				{
					MeterValueID = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("LastRev");
				if ((i >= 0))
				{
					LastRev = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				i = this.ColumnExistInHeader("Layer");
				if ((i >= 0))
				{
					Layer = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("CompiledExp");
				if ((i >= 0))
				{
					CompiledExp = ((byte[])(Convert.ChangeType(_strs[i], typeof(byte[]))));
				}
				i = this.ColumnExistInHeader("validexpression");
				if ((i >= 0))
				{
					validexpression = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				this.PostAddFromString(ref _log);
			}
			catch (SQLiteException sqlExc)
			{
				throw sqlExc;
			}
			catch (Exception Exc)
			{
				throw Exc;
			}
		}
		#endregion
	}
	
	public delegate void tblMeterChangedEventHandler(object sender, System.EventArgs e);
	
	public partial class tblMeterCollection : SQLiteTableCollection
	{
		
		/// <remarks>SQL Type:tblMeterChangedEventHandler</remarks>
		public event tblMeterChangedEventHandler tblMeterChanged;
		
		/// <remarks>Represents the foreign key object</remarks>
		private tblDisplay _DisplayID_tblDisplay;
		
		[Description("Represents the foreign key object of the type DisplayID")]
		public tblDisplay m_DisplayID_tblDisplay
		{
			get
			{
				return _DisplayID_tblDisplay;
			}
			set
			{
				_DisplayID_tblDisplay = value;
			}
		}
		
		[Description("Constructor")]
		public tblMeterCollection(tblDisplay _parent)
		{
			_DisplayID_tblDisplay = _parent;
		}
		
		[Description("Invoke the Changed event; called whenever list changes")]
		protected virtual void OntblMeterChanged(System.EventArgs e)
		{
			if (tblMeterChanged != null)
			{
				this.tblMeterChanged(this, e);
			}
		}
		
		[Description("Gets a  tblMeter from the collection.")]
		public tblMeter this[int index]
		{
			get
			{
				return ((tblMeter)(List[index]));
			}
			set
			{
				List[index] = value;
				this.OntblMeterChanged(EventArgs.Empty);
			}
		}
		
		[Description("Gets a  tblMeter from the collection.")]
		public tblMeter Get(int index)
		{
			return ((tblMeter)(List[index]));
		}
		
		[Description("Adds a new tblMeter to the collection.")]
		public void Add(tblMeter item)
		{
			List.Add(item);
			this.OntblMeterChanged(EventArgs.Empty);
		}
		
		[Description("Removes a tblMeter from the collection.")]
		public void Remove(tblMeter item)
		{
			List.Remove(item);
			this.OntblMeterChanged(EventArgs.Empty);
		}
		
		[Description("Inserts an tblMeter into the collection at the specified index.")]
		public void Insert(int index, tblMeter item)
		{
			List.Insert(index, item);
			this.OntblMeterChanged(EventArgs.Empty);
		}
		
		[Description("Returns the index value of the tblMeter class in the collection.")]
		public int IndexOf(tblMeter item)
		{
			return List.IndexOf(item);
		}
		
		[Description("Returns true if the tblMeter class is present in the collection.")]
		public bool Contains(tblMeter item)
		{
			return List.Contains(item);
		}
	}
}
