//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SQLite;


namespace DCS.DCSTables
{


    public partial class tblModbusServer : SQLiteTable
	{
		
		#region Static SQL String Memebers
		/// <remarks>This _databasename represents the full INSERT INTO string for the table tblModbusServer.</remarks>
		internal static string SQL_Insert = @"INSERT INTO [tblModbusServer] ([ControllerID], [ModbusServerNo], [LinkName], [LinkNo], [LinkType], [PortName], [RedPortName], [BaudRate], [Parity], [StopBit], [DataSize], [Redundant], [IP], [PortNumber], [StaNo], [Placement], [NoOfSlave], [Timeout], [NoOfRetry]) VALUES(@ControllerID, @ModbusServerNo, @LinkName, @LinkNo, @LinkType, @PortName, @RedPortName, @BaudRate, @Parity, @StopBit, @DataSize, @Redundant, @IP, @PortNumber, @StaNo, @Placement, @NoOfSlave, @Timeout, @NoOfRetry) ; select last_insert_rowid(); ";
		
		/// <remarks>This _databasename represents the full UPDATE string for the table tblModbusServer, with the WHERE clause.</remarks>
		internal static string SQL_Update = @"UPDATE [tblModbusServer] SET [ControllerID] = @ControllerID, [ModbusServerNo] = @ModbusServerNo, [LinkName] = @LinkName, [LinkNo] = @LinkNo, [LinkType] = @LinkType, [PortName] = @PortName, [RedPortName] = @RedPortName, [BaudRate] = @BaudRate, [Parity] = @Parity, [StopBit] = @StopBit, [DataSize] = @DataSize, [Redundant] = @Redundant, [IP] = @IP, [PortNumber] = @PortNumber, [StaNo] = @StaNo, [Placement] = @Placement, [NoOfSlave] = @NoOfSlave, [Timeout] = @Timeout, [NoOfRetry] = @NoOfRetry WHERE [ModbusServerID]=@ModbusServerID ";
		
		/// <remarks>This _databasename represents the full SELECT string for the table tblModbusServer, with the WHERE clause.</remarks>
		internal static string SQL_Select = @"SELECT [ControllerID], [ModbusServerNo], [LinkName], [LinkNo], [LinkType], [PortName], [RedPortName], [BaudRate], [Parity], [StopBit], [DataSize], [Redundant], [IP], [PortNumber], [StaNo], [Placement], [NoOfSlave], [Timeout], [NoOfRetry] FROM [tblModbusServer] WHERE [ModbusServerID]=@ModbusServerID ";
		
		/// <remarks>This _databasename represents the DELETE string for the table tblModbusServer, with the WHERE clause.</remarks>
		internal static string SQL_Delete = "DELETE FROM [tblModbusServer] WHERE [ModbusServerID]=@ModbusServerID ";
		#endregion
		
		#region Tables Memebers
		/// <remarks>SQL Type:System.Int64</remarks>
		private long _ModbusServerID = -1;
		
		[DisplayName("Modbus Server ID")]
		[Category("Primary Key")]
		public long ModbusServerID
		{
			get
			{
				return _ModbusServerID;
			}
			set
			{
				_ModbusServerID = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int64</remarks>
		private long _ControllerID = -1;
		
		[DisplayName("Controller ID")]
		[Category("Foreign Key")]
		public long ControllerID
		{
			get
			{
				return _ControllerID;
			}
			set
			{
				_ControllerID = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _ModbusServerNo;
		
		[DisplayName("Modbus Server No")]
		[Category("Column")]
		public short ModbusServerNo
		{
			get
			{
				return _ModbusServerNo;
			}
			set
			{
				_ModbusServerNo = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _LinkName = "";
		
		[DisplayName("Link Name")]
		[Category("Column")]
		public string LinkName
		{
			get
			{
				return _LinkName;
			}
			set
			{
				_LinkName = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _LinkNo;
		
		[DisplayName("Link No")]
		[Category("Column")]
		public short LinkNo
		{
			get
			{
				return _LinkNo;
			}
			set
			{
				_LinkNo = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _LinkType;
		
		[DisplayName("Link Type")]
		[Category("Column")]
		public short LinkType
		{
			get
			{
				return _LinkType;
			}
			set
			{
				_LinkType = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _PortName = "";
		
		[DisplayName("Port Name")]
		[Category("Column")]
		public string PortName
		{
			get
			{
				return _PortName;
			}
			set
			{
				_PortName = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _RedPortName = "";
		
		[DisplayName("Red Port Name")]
		[Category("Column")]
		public string RedPortName
		{
			get
			{
				return _RedPortName;
			}
			set
			{
				_RedPortName = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _BaudRate;
		
		[DisplayName("Baud Rate")]
		[Category("Column")]
		public short BaudRate
		{
			get
			{
				return _BaudRate;
			}
			set
			{
				_BaudRate = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _Parity = "";
		
		[DisplayName("Parity")]
		[Category("Column")]
		public string Parity
		{
			get
			{
				return _Parity;
			}
			set
			{
				_Parity = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _StopBit;
		
		[DisplayName("Stop Bit")]
		[Category("Column")]
		public short StopBit
		{
			get
			{
				return _StopBit;
			}
			set
			{
				_StopBit = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _DataSize;
		
		[DisplayName("Data Size")]
		[Category("Column")]
		public short DataSize
		{
			get
			{
				return _DataSize;
			}
			set
			{
				_DataSize = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _Redundant;
		
		[DisplayName("Redundant")]
		[Category("Column")]
		public short Redundant
		{
			get
			{
				return _Redundant;
			}
			set
			{
				_Redundant = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _IP = "";
		
		[DisplayName("IP")]
		[Category("Column")]
		public string IP
		{
			get
			{
				return _IP;
			}
			set
			{
				_IP = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _PortNumber;
		
		[DisplayName("Port Number")]
		[Category("Column")]
		public short PortNumber
		{
			get
			{
				return _PortNumber;
			}
			set
			{
				_PortNumber = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _StaNo;
		
		[DisplayName("Sta No")]
		[Category("Column")]
		public short StaNo
		{
			get
			{
				return _StaNo;
			}
			set
			{
				_StaNo = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _Placement;
		
		[DisplayName("Placement")]
		[Category("Column")]
		public short Placement
		{
			get
			{
				return _Placement;
			}
			set
			{
				_Placement = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _NoOfSlave;
		
		[DisplayName("No Of Slave")]
		[Category("Column")]
		public short NoOfSlave
		{
			get
			{
				return _NoOfSlave;
			}
			set
			{
				_NoOfSlave = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _Timeout;
		
		[DisplayName("Timeout")]
		[Category("Column")]
		public short Timeout
		{
			get
			{
				return _Timeout;
			}
			set
			{
				_Timeout = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int16</remarks>
		private short _NoOfRetry;
		
		[DisplayName("No Of Retry")]
		[Category("Column")]
		public short NoOfRetry
		{
			get
			{
				return _NoOfRetry;
			}
			set
			{
				_NoOfRetry = value;
			}
		}
		#endregion
		
		#region Related Objects
		/// <remarks>Represents the foreign key object</remarks>
		private tblController _ControllerID_tblController;
		
		[Description("Represents the foreign key object of the type ControllerID")]
		public tblController m_ControllerID_tblController
		{
			get
			{
				return _ControllerID_tblController;
			}
			set
			{
				_ControllerID_tblController = value;
			}
		}
		#endregion
		
		#region Collection Objects
		/// <remarks>Lock for accessing collection</remarks>
		private readonly object _tblModbusServerDataCollectionLock = new object();
		
		/// <remarks>Represents the foreign key object</remarks>
		private tblModbusServerDataCollection _tblModbusServerDataCollection;
		
		[Description("Represents the foreign key object of the type ModbusServerID")]
		public tblModbusServerDataCollection m_tblModbusServerDataCollection
		{
			get
			{
              lock(_tblModbusServerDataCollectionLock)
              {
				if (_tblModbusServerDataCollection == null)
				{
					_tblModbusServerDataCollection =  new tblModbusServerDataCollection(this);
					_tblModbusServerDataCollection.Load();
				}
				return _tblModbusServerDataCollection;
              }
			}
			set
			{
				_tblModbusServerDataCollection = value;
			}
		}
		#endregion
		
		#region Public Methods
		public int Delete()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreDeleteTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				SQLiteCommand ComSync = Common.Conn.CreateCommand();
				Com.CommandText = tblModbusServer.SQL_Delete;
				ComSync.CommandText = "PRAGMA foreign_keys=ON";
				Com.Parameters.AddRange(GetSqlParameters());
				ComSync.ExecuteNonQuery();
				int rowseffected = Com.ExecuteNonQuery();
				ComSync.Dispose();
				Com.Dispose();
				this.PostDeleteTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Select()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblModbusServer.SQL_Select;
				Com.Parameters.AddRange(GetSqlParameters());
				SQLiteDataReader rs = Com.ExecuteReader();
				for (
				; rs.Read(); 
				)
				{
					AddFromRecordSet(rs);
				}
				rs.Close();
				rs.Dispose();
				Com.Dispose();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Insert()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreInsertTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblModbusServer.SQL_Insert;
				Com.Parameters.AddRange(GetSqlParameters());
				ModbusServerID = ((long)(Convert.ToInt64(Com.ExecuteScalar())));
				Com.Dispose();
				this.PostInsertTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Update()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreUpdateTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblModbusServer.SQL_Update;
				Com.Parameters.AddRange(GetSqlParameters());
				int rowseffected = Com.ExecuteNonQuery();
				Com.Dispose();
				this.PostUpdateTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public tblModbusServer()
		{
		}
		#endregion
		
		#region Private Methods
		private SQLiteParameter[] GetSqlParameters()
		{
			List<SQLiteParameter> SqlParmColl = new List<SQLiteParameter>();
			try
			{
				SqlParmColl.Add(CommonDB.AddSqlParm("@ModbusServerID", ModbusServerID, DbType.Int64));
				SqlParmColl.Add(CommonDB.AddSqlParm("@ControllerID", ControllerID, DbType.Int64));
				SqlParmColl.Add(CommonDB.AddSqlParm("@ModbusServerNo", ModbusServerNo, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@LinkName", LinkName, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@LinkNo", LinkNo, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@LinkType", LinkType, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@PortName", PortName, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@RedPortName", RedPortName, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@BaudRate", BaudRate, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Parity", Parity, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@StopBit", StopBit, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@DataSize", DataSize, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Redundant", Redundant, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@IP", IP, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@PortNumber", PortNumber, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@StaNo", StaNo, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Placement", Placement, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@NoOfSlave", NoOfSlave, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Timeout", Timeout, DbType.Int16));
				SqlParmColl.Add(CommonDB.AddSqlParm("@NoOfRetry", NoOfRetry, DbType.Int16));
				return SqlParmColl.ToArray();
			}
			catch (SQLiteException Exc)
			{
				throw Exc;
			}
		}
		
		public void AddFromRecordSet(SQLiteDataReader rs)
		{
			try
			{
				// if value from the recordset, to the ModbusServerID _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("ModbusServerID")) == false))
				{
					ModbusServerID = ((long)(Convert.ChangeType(rs["ModbusServerID"], typeof(long))));
				}
				// if value from the recordset, to the ControllerID _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("ControllerID")) == false))
				{
					ControllerID = ((long)(Convert.ChangeType(rs["ControllerID"], typeof(long))));
				}
				// if value from the recordset, to the ModbusServerNo _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("ModbusServerNo")) == false))
				{
					ModbusServerNo = ((short)(Convert.ChangeType(rs["ModbusServerNo"], typeof(short))));
				}
				// if value from the recordset, to the LinkName _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("LinkName")) == false))
				{
					LinkName = ((string)(Convert.ChangeType(rs["LinkName"], typeof(string))));
				}
				// if value from the recordset, to the LinkNo _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("LinkNo")) == false))
				{
					LinkNo = ((short)(Convert.ChangeType(rs["LinkNo"], typeof(short))));
				}
				// if value from the recordset, to the LinkType _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("LinkType")) == false))
				{
					LinkType = ((short)(Convert.ChangeType(rs["LinkType"], typeof(short))));
				}
				// if value from the recordset, to the PortName _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("PortName")) == false))
				{
					PortName = ((string)(Convert.ChangeType(rs["PortName"], typeof(string))));
				}
				// if value from the recordset, to the RedPortName _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("RedPortName")) == false))
				{
					RedPortName = ((string)(Convert.ChangeType(rs["RedPortName"], typeof(string))));
				}
				// if value from the recordset, to the BaudRate _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("BaudRate")) == false))
				{
					BaudRate = ((short)(Convert.ChangeType(rs["BaudRate"], typeof(short))));
				}
				// if value from the recordset, to the Parity _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Parity")) == false))
				{
					Parity = ((string)(Convert.ChangeType(rs["Parity"], typeof(string))));
				}
				// if value from the recordset, to the StopBit _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("StopBit")) == false))
				{
					StopBit = ((short)(Convert.ChangeType(rs["StopBit"], typeof(short))));
				}
				// if value from the recordset, to the DataSize _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("DataSize")) == false))
				{
					DataSize = ((short)(Convert.ChangeType(rs["DataSize"], typeof(short))));
				}
				// if value from the recordset, to the Redundant _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Redundant")) == false))
				{
					Redundant = ((short)(Convert.ChangeType(rs["Redundant"], typeof(short))));
				}
				// if value from the recordset, to the IP _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("IP")) == false))
				{
					IP = ((string)(Convert.ChangeType(rs["IP"], typeof(string))));
				}
				// if value from the recordset, to the PortNumber _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("PortNumber")) == false))
				{
					PortNumber = ((short)(Convert.ChangeType(rs["PortNumber"], typeof(short))));
				}
				// if value from the recordset, to the StaNo _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("StaNo")) == false))
				{
					StaNo = ((short)(Convert.ChangeType(rs["StaNo"], typeof(short))));
				}
				// if value from the recordset, to the Placement _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Placement")) == false))
				{
					Placement = ((short)(Convert.ChangeType(rs["Placement"], typeof(short))));
				}
				// if value from the recordset, to the NoOfSlave _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("NoOfSlave")) == false))
				{
					NoOfSlave = ((short)(Convert.ChangeType(rs["NoOfSlave"], typeof(short))));
				}
				// if value from the recordset, to the Timeout _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Timeout")) == false))
				{
					Timeout = ((short)(Convert.ChangeType(rs["Timeout"], typeof(short))));
				}
				// if value from the recordset, to the NoOfRetry _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("NoOfRetry")) == false))
				{
					NoOfRetry = ((short)(Convert.ChangeType(rs["NoOfRetry"], typeof(short))));
				}
			}
			catch (SQLiteException sqlExc)
			{
				throw sqlExc;
			}
			catch (Exception Exc)
			{
				throw Exc;
			}
		}
		
		public override void AddFromString(string[] _strs, string arg1, ref string _log)
		{
			try
			{
				this.PreAddFromString(ref _log);
				int i;
				i = this.ColumnExistInHeader("ControllerID");
				if ((i >= 0))
				{
					ControllerID = ((long)(Convert.ChangeType(_strs[i], typeof(long))));
				}
				i = this.ColumnExistInHeader("ModbusServerNo");
				if ((i >= 0))
				{
					ModbusServerNo = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("LinkName");
				if ((i >= 0))
				{
					LinkName = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("LinkNo");
				if ((i >= 0))
				{
					LinkNo = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("LinkType");
				if ((i >= 0))
				{
					LinkType = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("PortName");
				if ((i >= 0))
				{
					PortName = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("RedPortName");
				if ((i >= 0))
				{
					RedPortName = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("BaudRate");
				if ((i >= 0))
				{
					BaudRate = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("Parity");
				if ((i >= 0))
				{
					Parity = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("StopBit");
				if ((i >= 0))
				{
					StopBit = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("DataSize");
				if ((i >= 0))
				{
					DataSize = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("Redundant");
				if ((i >= 0))
				{
					Redundant = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("IP");
				if ((i >= 0))
				{
					IP = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("PortNumber");
				if ((i >= 0))
				{
					PortNumber = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("StaNo");
				if ((i >= 0))
				{
					StaNo = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("Placement");
				if ((i >= 0))
				{
					Placement = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("NoOfSlave");
				if ((i >= 0))
				{
					NoOfSlave = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("Timeout");
				if ((i >= 0))
				{
					Timeout = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				i = this.ColumnExistInHeader("NoOfRetry");
				if ((i >= 0))
				{
					NoOfRetry = ((short)(Convert.ChangeType(_strs[i], typeof(short))));
				}
				this.PostAddFromString(ref _log);
			}
			catch (SQLiteException sqlExc)
			{
				throw sqlExc;
			}
			catch (Exception Exc)
			{
				throw Exc;
			}
		}
		#endregion
	}
	
	public delegate void tblModbusServerChangedEventHandler(object sender, System.EventArgs e);
	
	public partial class tblModbusServerCollection : SQLiteTableCollection
	{
		
		/// <remarks>SQL Type:tblModbusServerChangedEventHandler</remarks>
		public event tblModbusServerChangedEventHandler tblModbusServerChanged;
		
		/// <remarks>Represents the foreign key object</remarks>
		private tblController _ControllerID_tblController;
		
		[Description("Represents the foreign key object of the type ControllerID")]
		public tblController m_ControllerID_tblController
		{
			get
			{
				return _ControllerID_tblController;
			}
			set
			{
				_ControllerID_tblController = value;
			}
		}
		
		[Description("Constructor")]
		public tblModbusServerCollection(tblController _parent)
		{
			_ControllerID_tblController = _parent;
		}
		
		[Description("Invoke the Changed event; called whenever list changes")]
		protected virtual void OntblModbusServerChanged(System.EventArgs e)
		{
			if (tblModbusServerChanged != null)
			{
				this.tblModbusServerChanged(this, e);
			}
		}
		
		[Description("Gets a  tblModbusServer from the collection.")]
		public tblModbusServer this[int index]
		{
			get
			{
				return ((tblModbusServer)(List[index]));
			}
			set
			{
				List[index] = value;
				this.OntblModbusServerChanged(EventArgs.Empty);
			}
		}
		
		[Description("Gets a  tblModbusServer from the collection.")]
		public tblModbusServer Get(int index)
		{
			return ((tblModbusServer)(List[index]));
		}
		
		[Description("Adds a new tblModbusServer to the collection.")]
		public void Add(tblModbusServer item)
		{
			List.Add(item);
			this.OntblModbusServerChanged(EventArgs.Empty);
		}
		
		[Description("Removes a tblModbusServer from the collection.")]
		public void Remove(tblModbusServer item)
		{
			List.Remove(item);
			this.OntblModbusServerChanged(EventArgs.Empty);
		}
		
		[Description("Inserts an tblModbusServer into the collection at the specified index.")]
		public void Insert(int index, tblModbusServer item)
		{
			List.Insert(index, item);
			this.OntblModbusServerChanged(EventArgs.Empty);
		}
		
		[Description("Returns the index value of the tblModbusServer class in the collection.")]
		public int IndexOf(tblModbusServer item)
		{
			return List.IndexOf(item);
		}
		
		[Description("Returns true if the tblModbusServer class is present in the collection.")]
		public bool Contains(tblModbusServer item)
		{
			return List.Contains(item);
		}
	}
}
