//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SQLite;


namespace DCS.DCSTables
{


    public partial class tblPlantStructureObject : SQLiteTable
	{
		
		#region Static SQL String Memebers
		/// <remarks>This _databasename represents the full INSERT INTO string for the table tblPlantStructureObject.</remarks>
		internal static string SQL_Insert = "INSERT INTO [tblPlantStructureObject] ([SoultionID], [Name], [Type], [Description" +
			"], [IsEquipment]) VALUES(@SoultionID, @Name, @Type, @Description, @IsEquipment) " +
			"; select last_insert_rowid(); ";
		
		/// <remarks>This _databasename represents the full UPDATE string for the table tblPlantStructureObject, with the WHERE clause.</remarks>
		internal static string SQL_Update = "UPDATE [tblPlantStructureObject] SET [SoultionID] = @SoultionID, [Name] = @Name, " +
			"[Type] = @Type, [Description] = @Description, [IsEquipment] = @IsEquipment WHERE" +
			" [ID]=@ID ";
		
		/// <remarks>This _databasename represents the full SELECT string for the table tblPlantStructureObject, with the WHERE clause.</remarks>
		internal static string SQL_Select = "SELECT [SoultionID], [Name], [Type], [Description], [IsEquipment] FROM [tblPlantS" +
			"tructureObject] WHERE [ID]=@ID ";
		
		/// <remarks>This _databasename represents the DELETE string for the table tblPlantStructureObject, with the WHERE clause.</remarks>
		internal static string SQL_Delete = "DELETE FROM [tblPlantStructureObject] WHERE [ID]=@ID ";
		#endregion
		
		#region Tables Memebers
		/// <remarks>SQL Type:System.Int64</remarks>
		private long _ID = -1;
		
		[DisplayName("ID")]
		[Category("Primary Key")]
		public long ID
		{
			get
			{
				return _ID;
			}
			set
			{
				_ID = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int64</remarks>
		private long _SoultionID = -1;
		
		[DisplayName("Soultion ID")]
		[Category("Foreign Key")]
		public long SoultionID
		{
			get
			{
				return _SoultionID;
			}
			set
			{
				_SoultionID = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _Name = "";
		
		[DisplayName("Name")]
		[Category("Column")]
		public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name = value;
			}
		}
		
		/// <remarks>SQL Type:System.Int32</remarks>
		private int _Type;
		
		[DisplayName("Type")]
		[Category("Column")]
		public int Type
		{
			get
			{
				return _Type;
			}
			set
			{
				_Type = value;
			}
		}
		
		/// <remarks>SQL Type:System.String</remarks>
		private string _Description = "";
		
		[DisplayName("Description")]
		[Category("Column")]
		public string Description
		{
			get
			{
				return _Description;
			}
			set
			{
				_Description = value;
			}
		}
		
		/// <remarks>SQL Type:System.Boolean</remarks>
		private bool _IsEquipment;
		
		[DisplayName("Is Equipment")]
		[Category("Column")]
		public bool IsEquipment
		{
			get
			{
				return _IsEquipment;
			}
			set
			{
				_IsEquipment = value;
			}
		}
		#endregion
		
		#region Related Objects
		/// <remarks>Represents the foreign key object</remarks>
		private tblSolution _SolutionID_tblSolution;
		
		[Description("Represents the foreign key object of the type SolutionID")]
		public tblSolution m_SolutionID_tblSolution
		{
			get
			{
				return _SolutionID_tblSolution;
			}
			set
			{
				_SolutionID_tblSolution = value;
			}
		}
		#endregion
		
		#region Public Methods
		public int Delete()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreDeleteTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				SQLiteCommand ComSync = Common.Conn.CreateCommand();
				Com.CommandText = tblPlantStructureObject.SQL_Delete;
				ComSync.CommandText = "PRAGMA foreign_keys=ON";
				Com.Parameters.AddRange(GetSqlParameters());
				ComSync.ExecuteNonQuery();
				int rowseffected = Com.ExecuteNonQuery();
				ComSync.Dispose();
				Com.Dispose();
				this.PostDeleteTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Select()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblPlantStructureObject.SQL_Select;
				Com.Parameters.AddRange(GetSqlParameters());
				SQLiteDataReader rs = Com.ExecuteReader();
				for (
				; rs.Read(); 
				)
				{
					AddFromRecordSet(rs);
				}
				rs.Close();
				rs.Dispose();
				Com.Dispose();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Insert()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreInsertTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblPlantStructureObject.SQL_Insert;
				Com.Parameters.AddRange(GetSqlParameters());
				ID = ((long)(Convert.ToInt64(Com.ExecuteScalar())));
				Com.Dispose();
				this.PostInsertTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public int Update()
		{
			try
			{
				if (Common.Conn == null)
				{
					Common.Conn = new SQLiteConnection(Common.ConnectionString);
					Common.Conn.Open();
				}
				this.PreUpdateTriger();
				SQLiteCommand Com = Common.Conn.CreateCommand();
				Com.CommandText = tblPlantStructureObject.SQL_Update;
				Com.Parameters.AddRange(GetSqlParameters());
				int rowseffected = Com.ExecuteNonQuery();
				Com.Dispose();
				this.PostUpdateTriger();
				return 0;
			}
			catch (SQLiteException ex)
			{
				return ex.ErrorCode;
			}
		}
		
		public tblPlantStructureObject()
		{
		}
		#endregion
		
		#region Private Methods
		private SQLiteParameter[] GetSqlParameters()
		{
			List<SQLiteParameter> SqlParmColl = new List<SQLiteParameter>();
			try
			{
				SqlParmColl.Add(CommonDB.AddSqlParm("@ID", ID, DbType.Int64));
				SqlParmColl.Add(CommonDB.AddSqlParm("@SoultionID", SoultionID, DbType.Int64));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Name", Name, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Type", Type, DbType.Int32));
				SqlParmColl.Add(CommonDB.AddSqlParm("@Description", Description, DbType.String));
				SqlParmColl.Add(CommonDB.AddSqlParm("@IsEquipment", IsEquipment, DbType.Boolean));
				return SqlParmColl.ToArray();
			}
			catch (SQLiteException Exc)
			{
				throw Exc;
			}
		}
		
		public void AddFromRecordSet(SQLiteDataReader rs)
		{
			try
			{
				// if value from the recordset, to the ID _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("ID")) == false))
				{
					ID = ((long)(Convert.ChangeType(rs["ID"], typeof(long))));
				}
				// if value from the recordset, to the SoultionID _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("SoultionID")) == false))
				{
					SoultionID = ((long)(Convert.ChangeType(rs["SoultionID"], typeof(long))));
				}
				// if value from the recordset, to the Name _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Name")) == false))
				{
					Name = ((string)(Convert.ChangeType(rs["Name"], typeof(string))));
				}
				// if value from the recordset, to the Type _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Type")) == false))
				{
					Type = ((int)(Convert.ChangeType(rs["Type"], typeof(int))));
				}
				// if value from the recordset, to the Description _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("Description")) == false))
				{
					Description = ((string)(Convert.ChangeType(rs["Description"], typeof(string))));
				}
				// if value from the recordset, to the IsEquipment _databasename is NOT null then set the value.
				if ((rs.IsDBNull(rs.GetOrdinal("IsEquipment")) == false))
				{
					IsEquipment = ((bool)(Convert.ChangeType(rs["IsEquipment"], typeof(bool))));
				}
			}
			catch (SQLiteException sqlExc)
			{
				throw sqlExc;
			}
			catch (Exception Exc)
			{
				throw Exc;
			}
		}
		
		public override void AddFromString(string[] _strs, string arg1, ref string _log)
		{
			try
			{
				this.PreAddFromString(ref _log);
				int i;
				i = this.ColumnExistInHeader("SoultionID");
				if ((i >= 0))
				{
					SoultionID = ((long)(Convert.ChangeType(_strs[i], typeof(long))));
				}
				i = this.ColumnExistInHeader("Name");
				if ((i >= 0))
				{
					Name = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("Type");
				if ((i >= 0))
				{
					Type = ((int)(Convert.ChangeType(_strs[i], typeof(int))));
				}
				i = this.ColumnExistInHeader("Description");
				if ((i >= 0))
				{
					Description = ((string)(Convert.ChangeType(_strs[i], typeof(string))));
				}
				i = this.ColumnExistInHeader("IsEquipment");
				if ((i >= 0))
				{
					IsEquipment = ((bool)(Convert.ChangeType(_strs[i], typeof(bool))));
				}
				this.PostAddFromString(ref _log);
			}
			catch (SQLiteException sqlExc)
			{
				throw sqlExc;
			}
			catch (Exception Exc)
			{
				throw Exc;
			}
		}
		#endregion
	}
	
	public delegate void tblPlantStructureObjectChangedEventHandler(object sender, System.EventArgs e);
	
	public partial class tblPlantStructureObjectCollection : SQLiteTableCollection
	{
		
		/// <remarks>SQL Type:tblPlantStructureObjectChangedEventHandler</remarks>
		public event tblPlantStructureObjectChangedEventHandler tblPlantStructureObjectChanged;
		
		/// <remarks>Represents the foreign key object</remarks>
		private tblSolution _SolutionID_tblSolution;
		
		[Description("Represents the foreign key object of the type SolutionID")]
		public tblSolution m_SolutionID_tblSolution
		{
			get
			{
				return _SolutionID_tblSolution;
			}
			set
			{
				_SolutionID_tblSolution = value;
			}
		}
		
		[Description("Constructor")]
		public tblPlantStructureObjectCollection(tblSolution _parent)
		{
			_SolutionID_tblSolution = _parent;
		}
		
		[Description("Invoke the Changed event; called whenever list changes")]
		protected virtual void OntblPlantStructureObjectChanged(System.EventArgs e)
		{
			if (tblPlantStructureObjectChanged != null)
			{
				this.tblPlantStructureObjectChanged(this, e);
			}
		}
		
		[Description("Gets a  tblPlantStructureObject from the collection.")]
		public tblPlantStructureObject this[int index]
		{
			get
			{
				return ((tblPlantStructureObject)(List[index]));
			}
			set
			{
				List[index] = value;
				this.OntblPlantStructureObjectChanged(EventArgs.Empty);
			}
		}
		
		[Description("Gets a  tblPlantStructureObject from the collection.")]
		public tblPlantStructureObject Get(int index)
		{
			return ((tblPlantStructureObject)(List[index]));
		}
		
		[Description("Adds a new tblPlantStructureObject to the collection.")]
		public void Add(tblPlantStructureObject item)
		{
			List.Add(item);
			this.OntblPlantStructureObjectChanged(EventArgs.Empty);
		}
		
		[Description("Removes a tblPlantStructureObject from the collection.")]
		public void Remove(tblPlantStructureObject item)
		{
			List.Remove(item);
			this.OntblPlantStructureObjectChanged(EventArgs.Empty);
		}
		
		[Description("Inserts an tblPlantStructureObject into the collection at the specified index.")]
		public void Insert(int index, tblPlantStructureObject item)
		{
			List.Insert(index, item);
			this.OntblPlantStructureObjectChanged(EventArgs.Empty);
		}
		
		[Description("Returns the index value of the tblPlantStructureObject class in the collection.")]
		public int IndexOf(tblPlantStructureObject item)
		{
			return List.IndexOf(item);
		}
		
		[Description("Returns true if the tblPlantStructureObject class is present in the collection.")]
		public bool Contains(tblPlantStructureObject item)
		{
			return List.Contains(item);
		}
	}
}
