//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SQLite;
using System.Data.SqlClient;
using System.Drawing;
using System.Text;
using System.Windows.Forms;


namespace DCS.DCSTables
{
	
	
	public partial class tblEWSUser 
	{
        public override bool PostDeleteTriger()
        {
            tblSolution.m_tblSolution().m_tblEWSUserCollection.Remove(this);
            return true;
        }

        public override bool PostInsertTriger()
        {

            tblSolution.m_tblSolution().m_tblEWSUserCollection.Add(this);
            return true;
        }
		
	}
	
	
	public partial class tblEWSUserCollection 
	{
        public override bool Load()
        {
            bool ret = true;
            try
            {
                if (Common.Conn == null)
                {
                    Common.Conn = new SQLiteConnection(Common.ConnectionString); 
                    Common.Conn.Open();
                }
                SQLiteDataReader myReader = null;
                SQLiteCommand myCommand = new SQLiteCommand();

           
                myReader = null;
                myCommand.CommandText = @"SELECT * FROM [tblEWSUser] ";
                myCommand.Connection = Common.Conn;
                myReader = myCommand.ExecuteReader();
                while (myReader.Read())
                {
                    tblEWSUser tblewsuser = new tblEWSUser();
                    tblewsuser.m_SolutionID_tblSolution = this.m_SolutionID_tblSolution;
                    tblewsuser.AddFromRecordSet(myReader);
                    this.Add(tblewsuser);
                }

                myReader.Close();
                myCommand.Dispose();


            }
            catch (SQLiteException ae)
            {
                System.Windows.Forms.MessageBox.Show(ae.Message);
                return false;
            }



            return ret;
        }
		
	}
}
