//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SQLite;
using System.Data.SqlClient;
using System.Drawing;
using System.Text;
using System.Windows.Forms;


namespace EWS.DCSTables
{


    public partial class tblFBDBlockPin
    {
        private bool PreDeleteTriger()
        {

            return true;
        }
        private bool PostDeleteTriger()
        {

            return true;
        }
        private bool PreInsertTriger()
        {

            return true;
        }
        private bool PostInsertTriger()
        {

            return true;
        }
        private bool PreUpdateTriger()
        {

            return true;
        }
        private bool PostUpdateTriger()
        {

            return true;
        }
    }
	
	
	public partial class tblFBDBlockPinCollection 
	{

        

        
        public bool Load()
        {
            bool ret = true;
            List<long> idlist = new List<long>();
            if (Common.Conn == null)
            {
                Common.Conn = new SQLiteConnection(Common.ConnectionString);
                Common.Conn.Open();
            }
            SQLiteDataReader myReader = null;
            SQLiteCommand myCommand = new SQLiteCommand();
            //if (_SqlConnectionConnection.State == System.Data.ConnectionState.Open)
            //    _SqlConnectionConnection.Close();
            //_SqlConnectionConnection.ConnectionString = Common.ConnectionString;
            //_SqlConnectionConnection.Open();
            try
            {
                myReader = null;
                myCommand.CommandText = @"SELECT * FROM [tblFBDBlockPin]  WHERE [FBDBlockID]= " + this.m_FBDBlockID_tblFBDBlock.FBDBlockID + ";"; // " order by oIndex;";
                myCommand.Connection = Common.Conn;
                myReader = myCommand.ExecuteReader();
                while (myReader.Read())
                {
                    idlist.Add(myReader.GetInt64(myReader.GetOrdinal("FBDBlockPinID")));      
                }

                myReader.Close();
                myCommand.Dispose();
                //_SqlConnectionConnection.Close();

                for (int i = 0; i < idlist.Count; i++)
                {
                    tblFBDBlockPin tblfbdblockpin = new tblFBDBlockPin();

                    tblfbdblockpin.FBDBlockPinID = idlist[i];
                    tblfbdblockpin.m_FBDBlockID_tblFBDBlock = this._FBDBlockID_tblFBDBlock;
                    tblfbdblockpin.Select();
                    this.Add(tblfbdblockpin);
                }

            }
            catch (SQLiteException ae)
            {
                return false;
                // MessageBox.Show(ae.Message.ToString());
            }



            return ret;
        }
	}
}
