//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SQLite;
using System.Data.SqlClient;
using System.Drawing;
using System.Text;
using System.Windows.Forms;


namespace DCS.DCSTables
{
	
	
	public partial class tblDINT 
    {
        ///// <remarks>This _databasename represents the full INSERT INTO string for the table tblDINT.</remarks>
        //string SQL_Insert_TXT = "INSERT INTO [tblDINT] ([SampleTime], [PointGroup], [UNI], [IRL], [IRH], [LL], [HH], [L], [H], [RTT], [Interval]) VALUES(@SampleTime, @PointGroup, @UNI, @IRL, @IRH, @LL, @HH, @L, @H, @RTT, @Interval) ; select last_insert_rowid(); ";

        ///// <remarks>This _databasename represents the full UPDATE string for the table tblDINT, with the WHERE clause.</remarks>
        //string SQL_Update_TXT = "UPDATE [tblDINT] SET [SampleTime] = @SampleTime, [PointGroup] = @PointGroup, [UNI] = @UNI, [IRL] = @IRL, [IRH] = @IRH, [LL] = @LL, [HH] = @HH, [L] = @L, [H] = @H, [RTT] = @RTT, [Interval] = @Interval WHERE [VarNameID]=@VarNameID ";

        ///// <remarks>This _databasename represents the full SELECT string for the table tblDINT, with the WHERE clause.</remarks>
        //string SQL_Select_TXT = "SELECT [SampleTime], [PointGroup], [UNI], [IRL], [IRH], [LL], [HH], [L], [H], [RTT], [Interval] FROM [tblDINT] WHERE [VarNameID]=@VarNameID ";

        ///// <remarks>This _databasename represents the DELETE string for the table tblDINT, with the WHERE clause.</remarks>
        //string SQL_Delete_TXT = "DELETE FROM [tblDINT] WHERE [VarNameID]=@VarNameID ";

        
	}
	
	
	public partial class tblDINTCollection 
    {

	}
}
